### ISSUE TITLE
Add support for SSIDs with spaces or special characters

### ISSUE THREAD

**Issue by NateHand93** [jajabro1/Ally-Bazzite-Helper-Scripts#1]
Currently, the scripts will fail if your SSID has a space or special character in it. My SSID, for instance, is IAmNotAVirusIPromise.bat and the scripts failed to work for me. The SSID needs to be wrapped in double quotes. I tried to make a PR to fix this but it looks like I don't have access to this repo, so here's the code:

#### BSSID_Lock.sh
```
#!/bin/bash
# Get the connected wifi Card Details and connected SSID/ BSSID
WIFI_CARD=$(nmcli dev status | grep wifi | grep -v disconnected | head -n1 | cut -d " " -f1)
LINK_INFO=$(iw dev $WIFI_CARD link)
BSSID=$(echo $LINK_INFO | grep -o -P '(?<=Connected to ).*(?= \(on)' | tr '[:lower:]' '[:upper:]') 
SSID=$(echo $LINK_INFO | grep -o -P '(?<=SSID: ).*(?= freq)')

# Lock Wifi to the BSSID to stop background scanning.
nmcli con mod "$SSID" 802-11-wireless.bssid $BSSID
nmcli dev dis $WIFI_CARD
nmcli dev con $WIFI_CARD
nmcli con mod "$SSID" 802-11-wireless.bssid ''
```

#### BSSID_Unlock.sh
```
#!/bin/bash
# Get the connected wifi Card Details and connected SSID/ BSSID
WIFI_CARD=$(nmcli dev status | grep wifi | grep -v disconnected | head -n1 | cut -d " " -f1)
LINK_INFO=$(iw dev $WIFI_CARD link)
BSSID=$(echo $LINK_INFO | grep -o -P '(?<=Connected to ).*(?= \(on)' | tr '[:lower:]' '[:upper:]') 
SSID=$(echo $LINK_INFO | grep -o -P '(?<=SSID: ).*(?= freq)')

# Lock Wifi to the BSSID to stop background scanning.
nmcli con mod "$SSID" 802-11-wireless.bssid ''
nmcli dev dis $WIFI_CARD
nmcli dev con $WIFI_CARD

```

**Comment by jajabro1** [comment]
Hey Nate! Thanks for the comment! Let me know if you want access to the repo, my intention is to have this open so maybe I need to fix some access issues so you don't have to fork it. That's a good catch, I would think a variable would ignore the symbols but if it works for you and secondly doesn't break anything I don't see why I wouldn't do this change.

**Comment by jajabro1** [comment]
I've made the changes currently, let me know if you find anything else. Thanks!
